### PR TITLE
reviewing css errors

### PR DESCRIPTION
**Pull request by angel-mora**
I AM VERY FRUSTRATED, STRUGGLING WITH SOME ISSUES.
I can not continue by myself and that's why I am asking this review.
Issues:
- In old commits I had the .big-header jquery transition to .header working fine and now it's not working. I have no coding partner and I've been more than 3 hours reviewing it and it's not working for no reason. I am very desperate, working on this for more than a month. Please help.
- Full screen newsweek logo working in firefox but not in Chrome
- In the morning I had sticky-top working fine but now it's not working anymore. I think something happened with the formatter in VSCode that messed my code but I can't really find it
- I used SASS to generate the css file. Do I need to debug the css or the sass file? Detailed instructions are very appreciated

PD. BOTH CONTRIBUTOR ACCOUNTS BELONG TO ME AND I CAN PROVE IT. THIS IS AN ISSUE WITH VSCODE I'VE BEEN HAVING FOR QUITE A LONG

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Nice job @angel-mora  👏👏👏

Your project looks awesome on the frontend, despite the issues you referenced.

However here are a few changes and tips I suggest you follow:

- [ ] Required - Fix linting issues on your CSS file. This project doesn't require the use of sass, but if you choose to use it you have to ensure your CSS has no linting error. SImply fix the linting errors in your sass files and this will reflect in your CSS file.

- [ ] Required- Add a logo to the page header. Rather than using the SVG you are currently using consider using a screenshot of the logo to prevent issues you are currently facing.

- [ ] Required - Also there are quite a ton of errors in your HTML file Kindly use this validator [tool](https://validator.w3.org/nu) to discover them and then fix them.

- [ ] Required - Make the top navbar fixed to the top on top of the page. It's absolutely not necessary for you to make the transition switch like the original webpage as this is not a javascript based project.
Simply make it fixed to the top. 

 * About the scroll.js you mentioned you can consider going through the git history of your files to discover where the error got in. You can go to this [link](https://www.toolsqa.com/git/git-history/), particularly the section with the title `How to view Git Commit History of specific intervals?`. Then do a `git checkout (add commit hash here)` to the actual file history you want.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by mikenath223 — APPROVED** [review]
### Great Job @angel-mora  👏👏👏

Glad you've made good on this project since the last review.

### STATUS: APPROVED ✅



I am approving this project because I trust you will make these changes before merging:

 - [ ] Add a live link to your readme. Kindly use this [tool](https://raw.githack.com/) to create a link.

- [ ] It almost seems you are following the Git flow pattern except you didn't make development your default branch. **DELETE THE DEVELOPMENT BRANCH**

**KINDLY ENSURE YOU MAKE THESE CHANGES BEFORE MERGING👍**

Once more great job fixing the issues.

Good luck with the next project. 🎉

**HAPPY CODING 👨‍💻**

**Comment by angel-mora** [comment]
errors addressed, ready for production. Thanks to microverse

**Pull request merged**
